repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of black
    hooks:
      - id: black


#  - repo: https://github.com/pycqa/flake8
#    rev: 6.1.0  # Use the latest stable version
#    hooks:
#      - id: flake8


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the latest version of mypy
    hooks:
      - id: mypy
