repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of black
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the latest version of mypy
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  # Use the latest stable version of isort
    hooks:
      - id: isort
