auth_post = {
    "id": "",
    "settingsId": 14325690,  # overwrite
    "frequency": "monthly",
    "serviceCode": "",
    "serviceCodeDescription": "",
    "serviceCodeId": 156484,  # overwrite
    "authorizedAmount": "",
    "authorizedUnits": "",
    "authorizedHours": "",
    "authorizedVisits": "",
    "totalAmount": "",
    "totalUnits": "",
    "totalHours": "",
    "totalVisits": "",
    "authorizedCode": "",
    "usageRestriction": "",
    "minMinutesPerUse": "",
    "maxMinutesPerUse": "",
    "sortOrder": "",
    "deletedDate": "",
    "deletedBy": "",
    "placeOfServiceId": "",
    "clientAcceptedHours": "",
    "clientAcceptedHoursFrequency": "weekly",
    "firstDayOfWeek": 0,
    "isIdInHash": False,
    "placeOfServiceList": [],
    "posUtil": {},
    "_utcOffsetMinutes": 300
}
