from datetime import datetime

from dacite import from_dict

from src.classes import API, AIOHTTPClientSession, Billing, CRSession, cr_types
from src.services.shared import get_cr_session


async def get_billings(
    client: AIOHTTPClientSession, client_id: int, start_date: str, end_date: str
):
    start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    end_dt = datetime.strptime(end_date, "%Y-%m-%d")
    session = await get_cr_session()
    res = session.post(
        API.BILLING.GET,
        json={
            "tasksPeriod": "",
            "tasksDate": "",
            "lastPaid": "",
            "lastBilled": "",
            "lockStatus": "",
            "copayStatus": "",
            "signedProvider": "",
            "signedClient": "",
            "creationDate": "",
            "startDate": "2024-09-05",
            "endDate": "2024-10-04",
            "search": "",
            "resourceId": "",
            "resourceName": "",
            "bundleLabelId": "",
            "bundleLabelName": "",
            "claimLabelId": "",
            "claimLabelName": "",
            "paymentLabelId": "",
            "paymentLabelName": "",
            "resourceLabelId": "",
            "resourceLabelName": "",
            "messageLabelId": "",
            "messageLabelName": "",
            "noteLabelId": "",
            "noteLabelName": "",
            "invoiceId": "",
            "invoiceName": "",
            "groupId": "",
            "groupName": "",
            "paymentReference": "",
            "paymentReferenceName": "",
            "principalId": "",
            "principalName": "",
            "managerId": "",
            "managerName": "",
            "implementerId": "",
            "implementerName": "",
            "billingId": "",
            "billingName": "",
            "referrerId": "",
            "referringName": "",
            "providerSupplierId": "",
            "providerSupplierName": "",
            "orderingId": "",
            "orderingName": "",
            "supervisingId": "",
            "supervisingName": "",
            "facilityId": "",
            "facilityName": "",
            "providerId": "",
            "providerName": "",
            "clientId": "1098265",
            "clientName": "",
            "contactId": "",
            "contactName": "",
            "createdByContactId": "",
            "createdByContactName": "",
            "billingEntryId": "",
            "billingEntryName": "",
            "feeScheduleId": "",
            "feeScheduleName": "",
            "insuranceId": "",
            "insuranceName": "",
            "locationId": "",
            "locationName": "",
            "insuranceCompanyId": "",
            "insuranceCompanyName": "",
            "sharedPayorId": "",
            "sharedPayorName": "",
            "creditCardId": "",
            "creditCardName": "",
            "serviceCodeId": "",
            "serviceCodeName": "",
            "invoiceType": "",
            "invoiceTypeName": "",
            "claimId": "",
            "claimName": "",
            "authorizationId": "",
            "authorizationName": "",
            "authorizationSettingsId": "",
            "authorizationSettingsName": "",
            "authorizationResourceId": "",
            "authorizationResourceName": "",
            "module": "",
            "moduleName": "",
            "shared": "",
            "channel": "",
            "channelDisplay": "",
            "action": "",
            "inactiveEmployees": "",
            "excludeInactiveClients": "",
            "authorId": "",
            "authorName": "",
            "state": "",
            "city": "",
            "zip": "",
            "zipName": "",
            "paymentTypeId": "",
            "paymentTypeName": "",
            "signed": "",
            "signedProviderName": "",
            "signedClientName": "",
            "assignedTo": "",
            "assignedToName": "",
            "assignedNotMoreThanThisManyDaysAgo": "",
            "assignedNotMoreThanThisManyDaysAgo_filterSummaryDisplayString": "",
            "completionPercent": "",
            "completionPercent_filterSummaryDisplayString": "",
            "deletedBy": "",
            "deletedByName": "",
            "createdBy": "",
            "createdByName": "",
            "lastUpdatedById": "",
            "lastUpdatedByName": "",
            "completedBy": "",
            "completedByName": "",
            "onBehalfOf": "",
            "onBehalfOfName": "",
            "appliedBy": "",
            "appliedByName": "",
            "taskId": "",
            "tasksFilter": "",
            "ticketsfromorg": "",
            "ticketsfromorgName": "",
            "templateIdLocal": "",
            "templateName": "",
            "internalCaseId": "",
            "billStatus": "",
            "billStatusName": "",
            "voidStatus": "",
            "voidStatusName": "",
            "lockStatusName": "",
            "copayStatusName": "",
            "course": "",
            "courseName": "",
            "courseDate": "",
            "courseDateName": "",
            "courseProvider": "",
            "courseProviderName": "",
            "lastBilledName": "",
            "lastPaidName": "",
            "resourceCount": "",
            "resourceCountName": "",
            "email": "",
            "filter": "",
            "filterName": "",
            "ado": "",
            "fileType": "",
            "fileTypeName": "",
            "sentBy": "",
            "sentByName": "",
            "sentTo": "",
            "sentToName": "",
            "age": "",
            "ageName": "",
            "gender": "",
            "genderName": "",
            "languageId": "",
            "languageName": "",
            "radius": "",
            "scopeId": "",
            "scopeName": "",
            "includeUnavailable": "",
            "frequency": "",
            "typeOpen": "",
            "typeClosed": "",
            "typeNone": "",
            "expires": "",
            "expiresDisplay": "",
            "effective": "",
            "period": "",
            "formId": "",
            "formName": "",
            "id": "",
            "typeId": "",
            "type": "",
            "domainId": "",
            "domain": "",
            "recordId": "",
            "record": "",
            "disciplineId": "",
            "discipline": "",
            "goalStatus": "",
            "goalStatusName": "",
            "responsibilityId": "",
            "responsibility": "",
            "assessmentId": "",
            "assessment": "",
            "goalAvgIntervention": "",
            "goalScoreRange": "",
            "goalScoreRangeName": "",
            "goalDuration": "",
            "duration": "",
            "goalTrend": "",
            "trend": "",
            "goalMethod": "",
            "method": "",
            "goalPhase": "",
            "phase": "",
            "goalActivity": "",
            "activity": "",
            "checknumber": "",
            "paymentId": "",
            "paymentName": "",
            "dateType": "",
            "isNew": "",
            "isNewName": "",
            "forceDateRange": "",
            "forceDateRangeName": "",
            "providerStatus": "",
            "providerStatusName": "",
            "clientStatus": "",
            "clientStatusName": "",
            "originFrom": "",
            "originFromName": "",
            "originBy": "",
            "originByName": "",
            "isDuplicate": "",
            "isDuplicateName": "",
            "isOverlapping": "",
            "isOverlappingName": "",
            "mismatchScheduleCode": "",
            "mismatchScheduleCodeName": "",
            "mismatchScheduleAuth": "",
            "mismatchScheduleAuthName": "",
            "mismatchScheduleDuration": "",
            "mismatchScheduleDurationName": "",
            "mismatchScheduleStartTime": "",
            "mismatchScheduleStartTimeName": "",
            "signedByAll": "",
            "signedByAllName": "",
            "unsigned": "",
            "signedByContactId": "",
            "signedByContactName": "",
            "unsignedByContactId": "",
            "unsignedByContactName": "",
            "messageId": "",
            "messageName": "",
            "templateId": "",
            "templateGroupId": "",
            "templateGroupName": "",
            "templateTypeId": "",
            "templateTypeName": "",
            "fileStatus": "",
            "fileStatusName": "",
            "contentLength": "",
            "contentLengthName": "",
            "versions": "",
            "versionsName": "",
            "effectiveDate": "",
            "effectiveDateName": "",
            "originModule": "",
            "originModuleName": "",
            "originAction": "",
            "originActionName": "",
            "authStartDate": "",
            "authStartDateName": "",
            "authEndDate": "",
            "authEndDateName": "",
            "isEarlyConversion": "",
            "isEarlyConversionName": "",
            "billingOrganizationId": "",
            "billingOrganizationName": "",
            "payments": "",
            "paymentsName": "",
            "paymentType": "",
            "paymentCopay": "",
            "paymentCopayName": "",
            "copayAny": "",
            "copayAnyName": "",
            "invoiceStatus": "",
            "invoiceStatusName": "",
            "entryStatus": "",
            "entryStatusName": "",
            "claimStatus": "",
            "claimStatusName": "",
            "authorized": "",
            "authorizedName": "",
            "timeWorkedInMinutes": "",
            "timeWorkedInMinutesName": "",
            "driveTimeInMinutes": "",
            "driveTimeInMinutesName": "",
            "mileage": "",
            "mileageName": "",
            "serviceLocation": "",
            "serviceLocationName": "",
            "serviceLocationId": "",
            "unitsOfService": "",
            "unitsOfServiceName": "",
            "rateClient": "",
            "rateClientName": "",
            "rateClientAgreed": "",
            "rateClientAgreedName": "",
            "rateClientDriveMileage": "",
            "rateClientDriveMileageName": "",
            "rateClientDriveHourly": "",
            "rateClientDriveHourlyName": "",
            "rateProvider": "",
            "rateProviderName": "",
            "rateProviderDriveMileage": "",
            "rateProviderDriveMileageName": "",
            "rateProviderDriveHourly": "",
            "rateProviderDriveHourlyName": "",
            "charges": "",
            "chargesName": "",
            "chargesAgreed": "",
            "chargesAgreedName": "",
            "owed": "",
            "owedName": "",
            "copay": "",
            "copayName": "",
            "notes": "",
            "notesName": "",
            "notesTherapy": "",
            "notesTherapyName": "",
            "calcType": "",
            "calcTypeName": "",
            "tasks": "",
            "tasksName": "",
            "modifierStatus": "",
            "modifierStatusName": "",
            "diagnosisCodeStatus": "",
            "diagnosisCodeStatusName": "",
            "diagnosisPointerStatus": "",
            "diagnosisPointerStatusName": "",
            "sort": "",
            "sortName": "",
            "changeDate": "",
            "changeDateName": "",
            "creationDateName": "",
            "unconvertedMatch": "",
            "unconvertedMatchName": "",
            "serviceCodeType": "",
            "serviceCodeTypeName": "",
            "paymentAdjustmentGroup": "",
            "paymentAdjustmentGroupName": "",
            "paymentAdjustmentReason": "",
            "paymentAdjustmentReasonName": "",
            "primaryPayor": "",
            "primaryPayorName": "",
            "primaryPayorStatus": "",
            "primaryPayorStatusName": "",
            "secondaryPayor": "",
            "secondaryPayorName": "",
            "secondaryPayorStatus": "",
            "secondaryPayorStatusName": "",
            "tertiaryPayor": "",
            "tertiaryPayorName": "",
            "tertiaryPayorStatus": "",
            "tertiaryPayorStatusName": "",
            "useVisitVerification": "",
            "useVisitVerificationName": "",
            "evvStatus": "",
            "evvStatusName": "",
            "amountType": "",
            "amountTypeName": "",
            "viewType": "",
            "viewTypeName": "",
            "totalsType": "",
            "totalsTypeName": "",
            "rangeType": "",
            "rangeTypeName": "",
            "validDays": "",
            "validDaysName": "",
            "expirationDate": "",
            "expirationDateName": "",
            "expirationFollowUp": "",
            "expirationFollowUpName": "",
            "enableValidation": "",
            "enableValidationName": "",
            "authorizationNumber": "",
            "authorizationNumberName": "",
            "allowOverBillHours": "",
            "allowOverBillHoursName": "",
            "allowOverBillUnits": "",
            "allowOverBillUnitsName": "",
            "allowOverBillVisits": "",
            "allowOverBillVisitsName": "",
            "allowOverBillAmount": "",
            "allowOverBillAmountName": "",
            "allowOverBillHoursTotal": "",
            "allowOverBillHoursTotalName": "",
            "allowOverBillUnitsTotal": "",
            "allowOverBillUnitsTotalName": "",
            "allowOverBillVisitsTotal": "",
            "allowOverBillVisitsTotalName": "",
            "allowOverBillAmountTotal": "",
            "allowOverBillAmountTotalName": "",
            "authorizedAmount": "",
            "authorizedAmountName": "",
            "authorizedHours": "",
            "authorizedHoursName": "",
            "authorizedUnits": "",
            "authorizedUnitsName": "",
            "authorizedVisits": "",
            "authorizedVisitsName": "",
            "totalAuthorizedAmount": "",
            "totalAuthorizedAmountName": "",
            "totalAuthorizedHours": "",
            "totalAuthorizedHoursName": "",
            "totalAuthorizedUnits": "",
            "totalAuthorizedUnitsName": "",
            "totalAuthorizedVisits": "",
            "totalAuthorizedVisitsName": "",
            "workedAmount": "",
            "workedAmountName": "",
            "workedHours": "",
            "workedHoursName": "",
            "workedUnits": "",
            "workedUnitsName": "",
            "workedVisits": "",
            "workedVisitsName": "",
            "totalWorkedAmount": "",
            "totalWorkedAmountName": "",
            "totalWorkedHours": "",
            "totalWorkedHoursName": "",
            "totalWorkedUnits": "",
            "totalWorkedUnitsName": "",
            "totalWorkedVisits": "",
            "totalWorkedVisitsName": "",
            "scheduledAmount": "",
            "scheduledAmountName": "",
            "scheduledHours": "",
            "scheduledHoursName": "",
            "scheduledUnits": "",
            "scheduledUnitsName": "",
            "scheduledVisits": "",
            "scheduledVisitsName": "",
            "totalScheduledAmount": "",
            "totalScheduledAmountName": "",
            "totalScheduledHours": "",
            "totalScheduledHoursName": "",
            "totalScheduledUnits": "",
            "totalScheduledUnitsName": "",
            "totalScheduledVisits": "",
            "totalScheduledVisitsName": "",
            "pendingAmount": "",
            "pendingAmountName": "",
            "pendingHours": "",
            "pendingHoursName": "",
            "pendingUnits": "",
            "pendingUnitsName": "",
            "pendingVisits": "",
            "pendingVisitsName": "",
            "totalPendingAmount": "",
            "totalPendingAmountName": "",
            "totalPendingHours": "",
            "totalPendingHoursName": "",
            "totalPendingUnits": "",
            "totalPendingUnitsName": "",
            "totalPendingVisits": "",
            "totalPendingVisitsName": "",
            "remainingAmount": "",
            "remainingAmountName": "",
            "remainingHours": "",
            "remainingHoursName": "",
            "remainingUnits": "",
            "remainingUnitsName": "",
            "remainingVisits": "",
            "remainingVisitsName": "",
            "totalRemainingAmount": "",
            "totalRemainingAmountName": "",
            "totalRemainingHours": "",
            "totalRemainingHoursName": "",
            "totalRemainingUnits": "",
            "totalRemainingUnitsName": "",
            "totalRemainingVisits": "",
            "totalRemainingVisitsName": "",
            "utilizationAmount": "",
            "utilizationAmountName": "",
            "utilizationHours": "",
            "utilizationHoursName": "",
            "utilizationUnits": "",
            "utilizationUnitsName": "",
            "utilizationVisits": "",
            "utilizationVisitsName": "",
            "totalUtilizationAmount": "",
            "totalUtilizationAmountName": "",
            "totalUtilizationHours": "",
            "totalUtilizationHoursName": "",
            "totalUtilizationUnits": "",
            "totalUtilizationUnitsName": "",
            "totalUtilizationVisits": "",
            "totalUtilizationVisitsName": "",
            "settingsCodeCount": "",
            "settingsCodeCountName": "",
            "view": "",
            "": "",
            "defaultRateNumber": "",
            "defaultRateNumberName": "",
            "defaultRateValue": "",
            "defaultRateValueName": "",
            "customRateNumber": "",
            "customRateNumberName": "",
            "labelNumber": "",
            "labelNumberName": "",
            "clientRateValue": "",
            "clientRateValueName": "",
            "providerRateValue": "",
            "providerRateValueName": "",
            "defaultRateStartDate": "",
            "defaultRateStartDateName": "",
            "defaultRateHasStartDate": "",
            "defaultRateHasStartDateName": "",
            "defaultRateEndDate": "",
            "defaultRateEndDateName": "",
            "defaultRateHasEndDate": "",
            "defaultRateHasEndDateName": "",
            "codeType": "",
            "codeTypeName": "",
            "appliedByContactId": "",
            "appliedByContactName": "",
            "isCopay": "",
            "isCopayName": "",
            "paidClaimId": "",
            "billingLabelIdCollection": [],
            "contactLabelIdCollection": [],
            "codeLabelIdCollection": [],
            "taskLabelIdCollection": [],
            "serviceTypeIdCollection": [],
            "serviceCategoryIdCollection": [],
            "advancedSearchMessageBus": {
                "subscriptions": [
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated-out-of-hash-cycle",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-value-displays-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated-out-of-hash-cycle",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-values-updated",
                        "active": True,
                    },
                    {
                        "source": "*",
                        "messageName": "search-value-displays-updated",
                        "active": True,
                    },
                ],
                "trackedSubscriptions": [],
            },
            "startDateDisplay": "2024-09-05",
            "endDateDisplay": "2024-10-04",
            "dateRange": "Sep 5 - Oct 4, 2024",
            "_advancedSearchPluginInitialized": True,
            "filterCount": 1,
            "page": 1,
            "pageSize": 50,
            "pageSizes": [50, 100, 150, 200, 250, 300, 350, 400, 450, 500],
            "tasksFilterOptions": {
                "overdue": ["Overdue", "overdue", "01-03-2025"],
                "today": ["Today", "day", "01-03-2025"],
                "tomorrow": ["Tomorrow", "day", "01-04-2025"],
                "thisweek": ["This week", "week", "12-30-2024"],
                "nextweek": ["Next week", "week", "01-06-2025"],
            },
            "creationDates": [
                {"name": "Today", "value": "eq|01/03/2025"},
                {"name": "Yesterday", "value": "eq|01/02/2025"},
                {"name": "Last 7 days", "value": "gt|12/26/2024"},
                {"name": "This month", "value": "eg|01/01/2025"},
                {"name": "Last month", "value": "bt|12/01/2024|12/31/2024"},
            ],
            "searchMaxDateRangeExceeded": False,
            "effectiveDisplay": "",
            "dateTypeDisplay": "",
            "dirtyProperties": ["startDate", "endDate", "clientId"],
            "isDirty": True,
            "queryDirty": True,
            "_syncingPageSize": False,
            "_syncingWithHash": False,
            "_collectionArr": [
                "billingLabelId",
                "contactLabelId",
                "codeLabelId",
                "taskLabelId",
                "serviceTypeId",
                "serviceCategoryId",
            ],
            "_staticSearchItems": [],
            "resetting": False,
            "billingLabelIds": "",
            "billingLabelIdIncluded": "",
            "billingLabelIdExcluded": "",
            "contactLabelIds": "",
            "contactLabelIdIncluded": "",
            "contactLabelIdExcluded": "",
            "codeLabelIds": "",
            "codeLabelIdIncluded": "",
            "codeLabelIdExcluded": "",
            "taskLabelIds": "",
            "taskLabelIdIncluded": "",
            "taskLabelIdExcluded": "",
            "serviceTypeIds": "",
            "serviceTypeIdIncluded": "",
            "serviceTypeIdExcluded": "",
            "serviceCategoryIds": "",
            "serviceCategoryIdIncluded": "",
            "serviceCategoryIdExcluded": "",
        },
    )
    if res.ok:
        data = res.json()
        print(
            {
                "dateRange": f"{start_dt.strftime('%b %d')} - {end_dt.strftime('%b %d')}, {end_dt.strftime('%Y')}",
                "clientId": client_id,
                "startdate": start_date,
                "enddate": end_date,
            }
        )
        billings: list[Billing] = [
            from_dict(data_class=Billing, data=billing)
            for billing in data.get("items", [])
        ]
        return billings
    else:
        return []


def set_billing_payor(session: CRSession, billing_id: int, insurance_id: int):
    return session.post(
        API.BILLING.SET_PAYOR,
        json={"id": billing_id, "insuranceId": insurance_id, "_utcOffsetMinutes": 300},
    ).json()


def get_client_payor(session: CRSession, client_id: int):
    return session.post(
        API.BILLING.GET_CLIENT_PAYORS,
        json={"clientIds": client_id, "_utcOffsetMinutes": 300},
    ).json()


def get_auth_codes(session: CRSession, billing: cr_types.Billing):
    return session.post(
        API.BILLING.GET_AUTH_CODES,
        json={
            "clientId": billing.ClientId,
            "providerId": billing.ProviderId,
            "dateOfService": billing.DateOfService,
            "segmentId": "",
            "includeRequiresConversion": True,
            "_utcOffsetMinutes": 300,
        },
    )
