name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DOMAIN_NAME }} >> ~/.ssh/known_hosts

    # Pull the latest changes on the VM
    - name: Deploy to VM
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.DOMAIN_NAME }} "
        bash &&
        cd cr-fn &&
        git pull origin main &&
        source myenv/bin/activate &&
        pip install -r requirements.txt &&
        sudo systemctl restart cr-bot &&
        sudo systemctl restart celery"